// @flow

export const FILTER = 'FILTER';
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const THREAD_FETCHED = 'THREAD_FETCHED';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const REPLY_COMMENT = 'REPLY_COMMENT';
export const CREATE_COMMENT = 'CREATE_COMMENT';
